name: node project

on:
  push:
  workflow_dispatch:
jobs:
  echo-node-setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '18'
      - name: Clean npm cache
        run: npm cache clean --force
          
      
